import { NativeModules } from 'react-native';
const { RNHealthKitWrapper } = NativeModules;
export default RNHealthKitWrapper;

export const HealthType = {
    BasalBodyTemperature: 'BasalBodyTemperature',
    BloodAlcoholContent: 'BloodAlcoholContent',
    BloodGlucose: 'BloodGlucose',
    BloodPressureDiastolic: 'BloodPressureDiastolic',
    BloodPressureSystolic: 'BloodPressureSystolic',
    BodyFatPercentage: 'BodyFatPercentage',
    BodyMass: 'BodyMass',
    BodyMassIndex: 'BodyMassIndex',
    BodyTemperature: 'BodyTemperature',
    ElectrodermalActivity: 'ElectrodermalActivity',
    ForcedExpiratoryVolume1: 'ForcedExpiratoryVolume1',
    ForcedVitalCapacity: 'ForcedVitalCapacity',
    HeartRate: 'HeartRate',
    HeartRateVariabilitySDNN: 'HeartRateVariabilitySDNN',
    Height: 'Height',
    LeanBodyMass: 'LeanBodyMass',
    OxygenSaturation: 'OxygenSaturation',
    PeakExpiratoryFlowRate: 'PeakExpiratoryFlowRate',
    PeripheralPerfusionIndex: 'PeripheralPerfusionIndex',
    RestingHeartRate: 'RestingHeartRate',
    RespiratoryRate: 'RespiratoryRate',
    UVExposure: 'UVExposure',
    VO2Max: 'VO2Max',
    WaistCircumference: 'WaistCircumference',
    WalkingHeartRateAverage: 'WalkingHeartRateAverage',

    SixMinuteWalkTestDistance: 'SixMinuteWalkTestDistance',
    StairAscentSpeed: 'StairAscentSpeed',
    StairDescentSpeed: 'StairDescentSpeed',
    WalkingSpeed: 'WalkingSpeed',
    WalkingDoubleSupportPercentage: 'WalkingDoubleSupportPercentage',
    WalkingAsymmetryPercentage: 'WalkingAsymmetryPercentage',
    WalkingStepLength: 'WalkingStepLength',

    AppleWalkingSteadiness: 'AppleWalkingSteadiness',

    AppleSleepingWristTemperature: 'AppleSleepingWristTemperature',
    AtrialFibrillationBurden: 'AtrialFibrillationBurden',
    HeartRateRecoveryOneMinute: 'HeartRateRecoveryOneMinute',
    RunningGroundContactTime: 'RunningGroundContactTime',
    RunningPower: 'RunningPower',
    RunningSpeed: 'RunningSpeed',
    RunningStrideLength: 'RunningStrideLength',
    RunningVerticalOscillation: 'RunningVerticalOscillation',
    UnderwaterDepth: 'UnderwaterDepth',
    WaterTemperature: 'WaterTemperature',

    // Cumulative
    ActiveEnergyBurned: 'ActiveEnergyBurned',
    AppleExerciseTime: 'AppleExerciseTime',
    BasalEnergyBurned: 'BasalEnergyBurned',
    DietaryBiotin: 'DietaryBiotin',
    DietaryCalcium: 'DietaryCalcium',
    DietaryCaffeine: 'DietaryCaffeine',
    DietaryCarbohydrates: 'DietaryCarbohydrates',
    DietaryChloride: 'DietaryChloride',
    DietaryCholesterol: 'DietaryCholesterol',
    DietaryChromium: 'DietaryChromium',
    DietaryCopper: 'DietaryCopper',
    DietaryEnergyConsumed: 'DietaryEnergyConsumed',
    DietaryFiber: 'DietaryFiber',
    DietaryFatMonounsaturated: 'DietaryFatMonounsaturated',
    DietaryFatPolyunsaturated: 'DietaryFatPolyunsaturated',
    DietaryFatSaturated: 'DietaryFatSaturated',
    DietaryFatTotal: 'DietaryFatTotal',
    DietaryFolate: 'DietaryFolate',
    DietaryIron: 'DietaryIron',
    DietaryIodine: 'DietaryIodine',
    DietaryMagnesium: 'DietaryMagnesium',
    DietaryManganese: 'DietaryManganese',
    DietaryMolybdenum: 'DietaryMolybdenum',
    DietaryNiacin: 'DietaryNiacin',
    DietaryPantothenicAcid: 'DietaryPantothenicAcid',
    DietaryPhosphorus: 'DietaryPhosphorus',
    DietaryPotassium: 'DietaryPotassium',
    DietaryProtein: 'DietaryProtein',
    DietaryRiboflavin: 'DietaryRiboflavin',
    DietarySelenium: 'DietarySelenium',
    DietarySodium: 'DietarySodium',
    DietarySugar: 'DietarySugar',
    DietaryThiamin: 'DietaryThiamin',
    DietaryVitaminA: 'DietaryVitaminA',
    DietaryVitaminB12: 'DietaryVitaminB12',
    DietaryVitaminB6: 'DietaryVitaminB6',
    DietaryVitaminC: 'DietaryVitaminC',
    DietaryVitaminD: 'DietaryVitaminD',
    DietaryVitaminE: 'DietaryVitaminE',
    DietaryVitaminK: 'DietaryVitaminK',
    DietaryWater: 'DietaryWater',
    DietaryZinc: 'DietaryZinc',
    DistanceCycling: 'DistanceCycling',
    DistanceDownhillSnowSports: 'DistanceDownhillSnowSports',
    DistanceSwimming: 'DistanceSwimming',
    DistanceWalkingRunning: 'DistanceWalkingRunning',
    DistanceWheelchair: 'DistanceWheelchair',
    FlightsClimbed: 'FlightsClimbed',
    InhalerUsage: 'InhalerUsage',
    InsulinDelivery: 'InsulinDelivery',
    NikeFuel: 'NikeFuel',
    NumberOfTimesFallen: 'NumberOfTimesFallen',
    PushCount: 'PushCount',
    StepCount: 'StepCount',
    SwimmingStrokeCount: 'SwimmingStrokeCount',

    AppleStandTime: 'AppleStandTime',

    AppleMoveTime: 'AppleMoveTime',

    NumberOfAlcoholicBeverages: 'NumberOfAlcoholicBeverages',

    // Continuous
    EnvironmentalAudioExposure: 'EnvironmentalAudioExposure',

    HeadphoneAudioExposure: 'HeadphoneAudioExposure',
}